" Filetype-specific indenting, syntax highlighting, omni-completion etc.
filetype plugin indent on

" Enable syntax highlighting
syntax on

" Allows matching with % on more than just ({[
runtime! macros/matchit.vim

" Automatic indenting for any filetype
set autoindent

" Better command-line completion
set wildmenu

" Show partial commands in the last line of the screen
set showcmd

" Highlight search hits
set hlsearch

" Search incrementally without pressing enter
set incsearch

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Allow backspacing over autoindent, line breaks and a start of insert action
set backspace=indent,eol,start

" Display the cursor position on the last line or in the status line of window
set ruler

" Always display the status line
set laststatus=2

" Instead of failing command because of unsaved changes, raise a dialog to ask
" for save
set confirm

" Don't make a sound or flash when doing something wrong
set visualbell
set t_vb=

" Enable the mouse in all modes
set mouse=a

" Set the command window height to 2 lines, to avoid having to press enter in
" some cases
set cmdheight=2

" Display line-numbers on the left
set number

" Indentation settings, use hard tabs - 4 spaces wide
set shiftwidth=4
set tabstop=4

" vim-plug plugins
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'rakr/vim-one'
Plug 'scrooloose/nerdtree'
call plug#end()

" Color scheme settings
colorscheme one
set background=dark
let g:airline_theme='one'
let g:airline_powerline_fonts=1

" True color support in iTerm
if (empty($TMUX))
  if (has("nvim"))
  "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif
