abbr -a -U -- - 'cd -'
abbr -a -U -- g git
abbr -a -U -- ga 'git add'
abbr -a -U -- gb 'git browse'
abbr -a -U -- gc 'git commit'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gd 'git diff'
abbr -a -U -- gf 'git fetch'
abbr -a -U -- gl 'git log --format=compact'
abbr -a -U -- gp 'git push'
abbr -a -U -- gpco 'git pr checkout'
abbr -a -U -- gpr 'git pull --rebase'
abbr -a -U -- gs 'git status -s'
abbr -a -U -- webserver 'python3 -m http.server'
