abbr -a -- - 'cd -'
abbr -a -- g git
abbr -a -- ga 'git add'
abbr -a -- gb 'git browse'
abbr -a -- gc 'git commit'
abbr -a -- gco 'git checkout'
abbr -a -- gd 'git diff'
abbr -a -- gf 'git fetch'
abbr -a -- gl 'git log --format=compact'
abbr -a -- gp 'git push'
abbr -a -- gpco 'git pr checkout'
abbr -a -- gpr 'git pull --rebase'
abbr -a -- gs 'git status -s'
abbr -a -- webserver 'python3 -m http.server'
