abbr g git
abbr ga 'git add'
abbr gc 'git commit'
abbr gd 'git diff'
abbr gs 'git status -s'
abbr webserver 'python3 -m http.server'
abbr -- - 'cd -'
abbr gco 'git checkout'
abbr gpr 'git pull --rebase'
abbr gf 'git fetch'
abbr gl 'git log --format=compact'
abbr gp 'git pull --rebase'
